<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-812TJVQ" ignored="0" name="Test" tests="7" failures="1" timestamp="2019-09-30T23:50:05 CDT" time="0.079" errors="0">
  <testcase name="additionV" time="0.011" classname="demo.Test1"/>
  <testcase name="details" time="0.001" classname="demo.Test1"/>
  <testcase name="details" time="0.001" classname="demo.Test1"/>
  <testcase name="details" time="0.001" classname="demo.Test1"/>
  <testcase name="rev" time="0.002" classname="demo.Test1"/>
  <testcase name="testCase1" time="0.001" classname="demo.Test1"/>
  <testcase name="testCase2" time="0.005" classname="demo.Test1">
    <failure type="java.lang.AssertionError" message="expected [7] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [9]
at demo.Test1.testCase2(Test1.java:25)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
</testsuite> <!-- Test -->
